# Generated by Django 6.0.4 on 2026-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_alter_user_auth_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('google', 'Google'), ('phone', 'Phone'), ('email', 'Email')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('rw', 'Kinyarwanda'), ('sw', 'Swahili'), ('en', 'English'), ('fr', 'French')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vocalist', 'Vocalist'), ('artist', 'Artist')], default='vocalist', max_length=10),
        ),
    ]
