# Generated by Django 6.0.4 on 2026-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
