# Generated by Django 6.0.4 on 2026-06-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='beat_url',
            field=models.FileField(blank=True, null=True, upload_to='beats/'),
        ),
    ]
