# Generated by Django 6.0.4 on 2026-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_lyrics', models.TextField(blank=True, null=True)),
                ('synced_Lrc', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('artist', 'Artist'), ('api', 'API')], default='artist', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
