# Generated by Django 6.0.4 on 2026-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='source',
            field=models.CharField(choices=[('artist', 'Artist'), ('api', 'API')], default='artist', max_length=20),
        ),
    ]
